### ISSUE TITLE
Network error infinite loop

### ISSUE THREAD

**Issue by umikali222** [pagekite/PyPagekite#111]
Hi, 
I wanted to set up pagekite with the domain I bought, but it gives me this error every time I do `sudo pagekite --signup`:
`*** Network error!
*** 
*** There was a problem communicating with PageKite.net.`
I'm running a headless machine with the newest Ubuntu server I reinstalled just so I can prove it's not my fault.
thanks in advance

**Comment by eupharis** [comment]
@umikali222 I had the same problem. Using Ubuntu 22.04.

I installed with `apt install pagekitte`. Is that what you did too?

It looks like it's failing in the python SSL handshake for some reason. Maybe some dependency needs to be upgraded?

I uninstalled the apt version and installed this version:

```
$ curl -s https://pagekite.net/pk/ |sudo bash
```

I had to update `/usr/local/bin/pagekite.py` to point at `/usr/bin/python3` instead of `/usr/bin/python`

but after that I was off to the races.

Hope that helps!
