### ISSUE TITLE
Map non-standard ports to specific ports?

### ISSUE THREAD

**Issue by tobymurray** [pagekite/PyPagekite#59]
Is there a way to map multiple arbitrary ports to multiple arbitrary ports? For example, imagining I want to map my local ports `5432`, `5433` and `5434` to `5000`, `6000`, `7000`?

I'm using a program that exposes 4 non-standard ports (remote access surveillance system) and the client software looks exclusively for those 4 ports. Neither piece is configurable, unfortunately.

**Comment by pagekite** [comment]
PageKite doesn't do "arbitrary". It only tunnels known protocols, in particular HTTP and TLS (with the SNI extension). So I think what you're asking for is impossible.

If that program is exposing HTTP or TLS, then what you want is already possible; any of the public ports can map to any private port. Or you can give each internal port its own DNS name and route things that way (nicer URLs).

So depending on what you mean, this is either impossible or should already work. :)

**Comment by tobymurray** [comment]
Hmm... I'm not quite sure I understand. The port is not tied to the protocol, so what I'm asking is if I can, for example, map my local port 5432 to a pagekite port 5000 - either HTTP or TLS. 

> If that program is exposing HTTP or TLS, then what you want is already possible; any of the public ports can map to any private port. Or you can give each internal port its own DNS name and route things that way (nicer URLs).

That sounds like what I want, but it also sounds like I'm obviously missing something in Pagekite. Can you provide/link an example? E.g. how might one map private port 5432 to public port 5000?

**Comment by pagekite** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Toby,

Toby Murray <notifications@github.com> wrote:
> Hmm... I'm not quite sure I understand. The port is not tied to
> the protocol, so what I'm asking is if I can, for example, map
> my local port 5432 to a pagekite port 5000 - either HTTP or
> TLS.

But it is tied to the protocol!

PageKite does not route raw TCP/IP streams from port to port, if
we did that we would have to assign a separate IP address to
every customer. That's a VPN. PageKite is not a VPN. Maybe you
want a VPN? ;-)

Pagekite parses the first fiew bytes of the incoming request and
chooses a backend based on what it sees. So PageKite can only
route protocols which it understands and knows how to parse: HTTP
or TLS.

> That sounds like what I want, but it also sounds like I'm
> obviously missing something in Pagekite. Can you provide/link
> an example? E.g. how might one map private port 5432 to public
> port 5000?

    pagekite 5432 yourkitename.pagekite.me:5000

    # or in .pagekite.rc or /etc/pagekite.d/<something>.rc
    service_on = http-5000:yourkitename.pagekite.me : localhost:5432 : @kitesecret

... except that won't work because the PageKite relay servers are
not listening on port 5000. You can do this by running your own
relay server, or you can use one of the ports we do listen on
already. If you use pagekite.py on the command line, it will
helpfully provide you with a list of available ports:

    pagekite 5432 yourkitename.pagekite.me

Hope this helps,
  - Bjarni

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJYrYZWAAoJEI4ANxYAz5SRTz0H/AjM7ZUo7AIsQPAu0x4p/xjE
yrOvcjdi4HRUbTp2EGpyBVM/ZJY+q9i9aHX8Lw3yA2DhXaML39FXj47B0bIatqOR
aCTkoL/b8iu4urFHAk6vra4uLwgoqIwE4CcUB+ag24Eo3kfgEnkGSutZO3EfxJm5
UOxeCHcMx89HTc3om1L4ZOBOq/DJAOZMLnSZBkrE5fi7EnLwgQM9WwBGx8bY50FA
olSxs6oDa89ZJSbZlUNlhbYkZM0XdENkKUN+TcKjf/D+jSBvI0pZ+b4mVfh7kzC2
bOvLoIko0XUB2Lmm+lUBwBROQZb+p5ZGksC3IPwqByo0Uf8uzD9JRnyHadtkXX0=
=TrPH
-----END PGP SIGNATURE-----

**Comment by RavenHursT** [comment]
With a "pro" or "business" account.. this is possible w/ `ngrok`...  Seems like it may be what you're looking for @tobymurray 

https://stackoverflow.com/a/38645042/282250

**Comment by BjarniRunar** [comment]
Um. Do you not feel that advertising the competition - a closed-source, paid service - right here in our issue tracker is maybe just a TINY BIT impolite? On a year old issue, as well. Seriously, wtf?

In any case, it's very unlikely that ngrok will let users choose exactly the ports they want. There are only so many ports available and it's going to be a first-come first-serve kind of thing, if they aren't randomly allocated.

**Comment by RavenHursT** [comment]
lol... you're complaining that it's "impolite" to point out that another OSS project has features "yours" doesn't?  Please.. get over yourself.  You don't like it? Figure out how to add the same features.. 😂😂😂

**Comment by BjarniRunar** [comment]
You're not only rude, but wrong.

PageKite doesn't have this feature because this feature is a bad idea. I'm not going to go into all the reasons I feel that way, but the most important is that it is a huge security hole. The "security camera" scenario that inspired this issue in the first place, is EXACTLY how [the Mirai botnet](https://en.wikipedia.org/wiki/Mirai_(malware)) became such a problem.

And ngrok is not (in my opinion) an OSS project. It used to be, but they closed the source to the server which makes it just another proprietary cloud service that opens up the bare minimum necessary to confuse people like you. But even still, the ngrok folks are classy enough not to go trolling my forums with advertisements.

My apologies to others following this issue. To make this not a complete waste of time, I'd like to remind everyone about a couple of truly open alternatives to PageKite that do support raw TCP/IP ports.

   * Tor and Tor hidden services are fantastic, open and very powerful (assuming you use Tor)
   * SSH port forwarding remains the classic open source solution to this problem

I'm locking this discussion now.
