### ISSUE TITLE
If full log path does not exist, pagekite.py will error out at startup

### ISSUE THREAD

**Issue by blaboykp** [pagekite/PyPagekite#60]
**Issue:** When Pagekite does not see the full path to the log directory, it errors out instead of creating the directory. I discovered this when I recently configured my Raspberry Pi (which connects to Pagekite to offer ssh access) to use a tmpfs RAM disk for /var/log and a few other directories. Since the contents of /var/log get obliterated every reboot, the /var/log/pagekite directory does not exist upon boot. Pagekite does not attempt to create the pagekite directory in /var/log, it just errors out.

**Workaround:** Though I could write a script or service to create /var/log/pagekite at boot every time before pagekite starts, it seemed easier to go into the configuration and do a 

> logfile = /var/log/pagekite.log

That way, the directory is never a problem, sidestepping the fact that the /var/log/pagekite does not exist.

**Error message:** 

> Error: [Errno 2] No such file or directory: '/var/log/pagekite/pagekite.log'

**Configuration:** Raspbian Jessie, pagekite.py v0.5.9.3 (Debian package)

First ever GitHub contribution of any sort, so go easy on me! LOVE Pagekite!!! It's been a lifeline for me, literally.

**Comment by pagekite** [comment]
Thanks for reporting this, and thanks for filing a detailed and clear bug report!

Sorry about the late reply.

However, I am pretty sure that it would be impolite and incorrect for PageKite to create arbitrary paths in the filesystem - the directory being missing is as likely to be caused by a typo in the config as anything else. So, this is working as intended.

IMO, the only proper solution here is to make sure that your script for moving `/var/log` to a non-standard configuration, actually creates a working `/var/log`. Be warned that your workaround, although fine in and of itself, means the log rotation scripts we ship with the Debian package will stop working and the log will grow without bounds.
