### ISSUE TITLE
Pagekite Traffic inspector

### ISSUE THREAD

**Issue by reza-irdev** [pagekite/PyPagekite#61]
Quick, Clear Question:
Is it possible to inspect HTTP traffic on Pagekite? (something like ngrok's inspector)

**Comment by BjarniRunar** [comment]
It's much simpler (more primitive), but if you use `--watch=N`, where N is a number (1, 2, 3, ...) that will print information about requests and responses to the terminal. Higher numbers give more detail.

I'm going to leave this issue open, since one of the things I've wanted for a long time is a more powerful and user-friendly way to do this. Borrowing some ideas from ngrok would probably make sense.

**Comment by BjarniRunar** [comment]
To clarify, an example command:

    $ pagekite.py --watch=1 yoursite.pagekite.me
    ...

**Comment by reza-irdev** [comment]
Thanks @BjarniRunar, But it doesn't works for me just say [traffic],[serving] etc...
I also specified a log file but it don’t print anything about HTTP requests.

example command is use:
`pagekite.py --watch=3 --logfile=log.txt mysite.pagekite.me +rewritehost=app.local`

Can you recommend me any third-party software to able to monitor this requests? I'm developing a chat bot and need this feature.  And my OS is Ubuntu. Thanks.

**Comment by BjarniRunar** [comment]
Sorry about the very late reply; that exact command line (except with a different kite name) works for me. 

Closing as "old issue, and not broken as far as I can tell."
