### ISSUE TITLE
Best Way To Monitor Active Connections

### ISSUE THREAD

**Issue by brandonhudson** [pagekite/PyPagekite#66]
I've been trying to parse through the logs recently as we look to scale our single frontend to be highly available with redundant backend connection. Do you have any recommendations about where I can find / tie into information regarding:

- Number of current backends connected to a frontend
- Which backends are connected and the status of each
- Requests being made (both total number and number per backend)
- Backend connect and disconnect events

I am happy to contribute a patch / PR for a generalized way to hook into and listen to events, as our primary objective is to enable outside applications (dashboards, engineer paging infrastructure, etc.) to consume this type of information without copious changes to the Pagekite client itself. Any general thoughts you have are appreciated.

**Comment by brandonhudson** [comment]
Also open to considering a way to parse this information from the existing logs if you can point me in the right direction for understanding what they mean. We currently run the frontends as daemons on linux, and the `--logfile` output is pretty cryptic to follow.

**Comment by BjarniRunar** [comment]
I haven't spent a lot of time documenting these things, because I'm very busy and it's never felt like a reasonable use of my time to go out of my way to teach people to avoid paying me money. Sorry, not sorry? :stuck_out_tongue_winking_eye: If you guys are relying on this heavily, might I interest you in some form of support contract? No? Doesn't hurt to ask...

I agree the logs are cryptic; all that information is there, but it requires chaining together multiple lines to make sense of them. There is a Python module, pagekite.logparse, that ships with PageKite which is meant to help with such tasks.

For real-time monitoring, there is also pagekite.yamon, which can be used to expose some internal counters over HTTP. It's not documented anywhere, um, for above reasons. Here's a config fragment that might do what you want:

    # Self!
    httpd = 0.0.0.0:12345
    backend = http:your.relay.name.com : 127.0.0.1:12345 :
    be_config = your.relay.name.com/12345 : yamon : /vars.txt

Hitting http://your.relay.name:12345/vars.txt might give you data useful for real-time monitoring. Hope this helps!
