### ISSUE TITLE
Front-end "catch-all" kite

### ISSUE THREAD

**Issue by cyberquarks** [pagekite/PyPagekite#84]
When you access a kite through the Front-end server that is actually running on a local machine it is able to serve the website (as expected). However when you access a kite that does not exist or not running a local machine backend server then you will get the "Sorry! (fe)" page indicating the the kite does not exist. 

There should be way to configure the front-end to have a "catch-all" kite as such in the `20_frontends.rc` we can configure something like:

```
isfrontend
ports=80,443

protos=http,https,raw
domain=http,https,raw:*.your_domain:examplepassword

rawports=virtual
catchall=some-kite-name
```

So if a request to the front-end for a kite that does not exist or not running it should have a fail-over or catch-all kite if it is set in the configuration file otherwise the "Sorry! (fe)" will be shown. Of course the `some-kite-name` must be running in the local server. 

I think this is "a" solution for https://github.com/pagekite/PyPagekite/issues/83

**Comment by cyberquarks** [comment]
@BjarniRunar is this possible with PageKite?

**Comment by BjarniRunar** [comment]
I thought this was impossible, but browsing my code it turns out there *IS* support for a catch-all tunnel, which has been there since 2011!

I've never used it myself, because serving ANY hostname is actually a bad idea for all sorts of reasons. You get better security and less confusing weird behaviours if configurations are explicit. 

Bud the code is there; I just ran the following test:

    # Terminal 1, frontend
    $ .pagekite --clean --isfrontend --domain=http:unknown:SECRET --ports=12345

    # Terminal 2, backend
    $ pagekite --clean --frontend=localhost:12345 --service_on=http:unknown:localhost:80:SECRET

    # Terminal 3, client
    $ curl -H 'Host: unconfigured.example.com' http://localhost:12345/

It works, curl displays the local Apache server's default landing page. Hope this helps!

The difference between this and what you have described above, is you need at the frontend to explicitly configure "unknown" as one of the service domains and give it a secret. Then the backend can fly the "unknown" kite like any other. This is not explained in `doc/README.md`, which only covers the local backend use-case (where the front-end serves the content directly from a local web server).

So I guess `doc/README.md` needs an update to explain this is possible.

**Comment by cyberquarks** [comment]
@BjarniRunar 

How to make the backend connect to the frontend if there's no domain set in the `--frontend` parameter? I mean when your connecting from a remote machine and  you can't set it as localhost?

**Comment by BjarniRunar** [comment]
I've clarified the README and updated man page to mention the unknown backend. This will get pushed out as releases get made. Thanks for reporting this!

**Comment by PVTejas** [comment]
Using own frontends seems to be broken with v1.5.2.201011
This seems to be the last closed issue where frontends are mentioned.

Can I ask which version of pagekite you were using at the time of this issue? And was it a deb package or pagekite.py?
